name: Build CRandom

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setpu-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Publish
      run: |
        cd CRandom
        dotnet puclish -c Release -o publish
