name: Build CRandom

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Publish
      run: |
        cd CRandom_n-c-cs
        dotnet publish -c Release -o publish_windows
        dotnet publish -c Release -o publish_osx -r osx.10.11-x64 --self-contained true /p:PublishTrimmde=true /p:Publish
        dotnet publish -c Release -o publish_linux -r linux-x64 --self-contained true /p:PublishTrimmde=true /p:Publish

    - name: Windows Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Windows Artifacts
        path: CRandom_n-c-cs/publish_windows

    - name: Mac Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Mac Artifacts
        path: CRandom_n-c-cs/publish_osx

    - name: Linux Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Linux Artifacts
        path: CRandom_n-c-cs/publish_linux
