name: Build CRandom

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Publish
      run: |
        cd CRandom_n-c-cs
        dotnet publish -c Release -o publish

    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: CRandom_n-c-cs/publish
